# Generated by Django 4.0.1 on 2022-01-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='button_text',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='headline',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='photo',
            field=models.ImageField(default=' ', upload_to='media/slider/%Y/'),
        ),
        migrations.AddField(
            model_name='slider',
            name='subtitle',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
