# Generated by Django 4.0.1 on 2022-01-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_slider_button_text_slider_headline_slider_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
