# Generated by Django 4.0.1 on 2022-01-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_slider_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('role', models.CharField(max_length=100, null=True)),
                ('fb_link', models.CharField(max_length=255, null=True)),
                ('insta_link', models.CharField(max_length=255, null=True)),
                ('photo', models.ImageField(upload_to='media/team/%Y/%m/%d/')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='slider',
            name='photo',
            field=models.ImageField(default='', upload_to='media/slider/%Y/'),
        ),
    ]
