# Generated by Django 4.0.1 on 2022-01-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_team_alter_slider_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='channel_link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
